### ISSUE TITLE
Impossible to assign png format to snapshots

### ISSUE THREAD

**Issue by nvasta** [jmmluna/ol-map-screenshot#9]
The 'png' format parameter doesn't seem to work.

After having a quick look at the MapExporter.js code I found the following:

`
if (param.format)
            format = param.format.toLowerCase() === 'PNG' ? 'image/png' : format;
`

This doesn't make much sense does it?

**Comment by jmmluna** [comment]
Hi Nikolaos,

you are absolutely right about the PNG format issue. I'll fix it and run the tests, and let you know once the fix is available.

Thank you very much for your contribution.

Best regards

**Comment by jmmluna** [comment]
Version 1.0.2 is now available!!

**Comment by nvasta** [comment]
Awesome!, Thanks for the quick fix!
